backend:
  name: git-gateway
  branch: publish

aliases:
  copyright: &copyright "Zane Adickes 2019"
  categories: &categories [
    "_blank_",
    "Arts",
    "Arts:Design",
    "Arts:Fashion & Beauty",
    "Arts:Food",
    "Arts:Literature",
    "Arts:Performing Arts",
    "Arts:Visual Arts",
    "Business",
    "Business:Business News",
    "Business:Careers",
    "Business:Investing",
    "Business:Management & Marketing",
    "Business:Shopping",
    "Comedy",
    "Education",
    "Education:Educational Technology",
    "Education:Higher Education",
    "Education:K-12",
    "Education:Language Courses",
    "Education:Training",
    "Games & Hobbies",
    "Games & Hobbies:Automotive",
    "Games & Hobbies:Aviation",
    "Games & Hobbies:Hobbies",
    "Games & Hobbies:Other Games",
    "Games & Hobbies:Video Games",
    "Government & Organizations",
    "Government & Organizations:Local",
    "Government & Organizations:National",
    "Government & Organizations:Non-Profit",
    "Government & Organizations:Regional",
    "Health",
    "Health:Alternative Health",
    "Health:Fitness & Nutrition",
    "Health:Self-Help",
    "Health:Sexuality",
    "Kids & Family",
    "Music",
    "News & Politics",
    "Religion & Spirituality",
    "Religion & Spirituality:Buddhism",
    "Religion & Spirituality:Christianity",
    "Religion & Spirituality:Hinduism",
    "Religion & Spirituality:Islam",
    "Religion & Spirituality:Judaism",
    "Religion & Spirituality:Other",
    "Religion & Spirituality:Spirituality",
    "Science & Medicine",
    "Science & Medicine:Medicine",
    "Science & Medicine:Natural Sciences",
    "Science & Medicine:Social Sciences",
    "Society & Culture",
    "Society & Culture:History",
    "Society & Culture:Personal Journals",
    "Society & Culture:Philosophy",
    "Society & Culture:Places & Travel",
    "Sports & Recreation",
    "Sports & Recreation:Amateur",
    "Sports & Recreation:College & High School",
    "Sports & Recreation:Outdoor",
    "Sports & Recreation:Professional",
    "Technology",
    "Technology:Gadgets",
    "Technology:Tech News",
    "Technology:Podcasting",
    "Technology:Software How-To",
    "TV & Film",
  ]

collections:
  - label: "Podcast"
    name: "podcast"
    files:
      - label: "Podcast Details"
        name: "podcastDetails"
        file: "src/cms/podcast-details.md"
        fields:
        - { label: "Collection", name: "collection", widget: "hidden", default: "podcast"}
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Description", name: "description", widget: "string" }
        - { label: "Cover Art", name: "image_url", widget: "image" }
        - { label: "Publish Date", name: "pubDate", widget: "datetime" }
        - { label: "Copyright", name: "copyright", widget: "string", default: *copyright, required: false }
        - label: "Itunes Specifics"
          name: "itunesPodcastData"
          widget: "object"
          fields:
            - { label: "Author", name: "author", widget: "relation", collection: "crew", searchFields: ["name"], valueField: "name" }
            - { label: "Owner", name: "owner", widget: "relation", collection: "crew", searchFields: ["name"], valueField: "name", required: false }
            - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
            - { label: "Type", name: "type", widget: "select", default: "Episodic", options: ["Episodic", "Serial"] }
            - { label: "Category 1", name: "category1", widget: "select", options: *categories, default: "_blank_" }
            - { label: "Category 2", name: "category2", widget: "select", options: *categories, default: "_blank_" }
            - { label: "Category 3", name: "category3", widget: "select", options: *categories, default: "_blank_" }
            - { label: "Explicit", name: "explicit", widget: "boolean", default: false }
            - { label: "Block", name: "block", widget: "boolean", default: false }

  - label: Crew
    name: crew
    folder: src/cms/collections/crew
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - { label: Collection, name: "collection", widget: "hidden", default: "crew1"}
      - { label: Name, name: "name", widget: "string" }
      - { label: Title, name: "title", widget: "string" }
      - { label: Email, name: "email", widget: "string" }
      - { label: Photo, name: "image", widget: "image" }
  
  - label: "Guests"
    name: "guests"
    folder: "src/cms/collections/guests"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Collection", name: "collection", widget: "hidden", default: "guests"}
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Photo", name: "image", widget: "image" }

  - label: "Episodes"
    name: "episodes"
    folder: "src/cms/collections/episodes"
    create: true
    slug: "{{slug}}" # {{year}}-{{month}}-{{day}}-{{slug}}
    fields:
      - { label: "Collection", name: "collection", widget: "hidden", default: "episodes"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "File Location", name: "file_location", widget: "string" }
      - { label: "Duration", name: "duration", widget: "duration"}
      - { label: "Cover Art", name: "image", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - label: "Itunes Metadata"
        name: "itunesEpisodeData"
        widget: "object"
        fields:
          - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
          - { label: "Summary", name: "summary", widget: "string", required: false }
          - { label: "Type", name: "type", widget: "select", default: "Full", options: ["Full", "Bonus", "Trailer"] }
          - { label: "Author", name: "author", widget: "relation", collection: "crew", searchFields: ["name"], valueField: "name", required: false }
          - { label: "Explicit", name: "explicit", widget: "boolean", default: false }
          - { label: "Block", name: "block", widget: "boolean", default: false }

media_folder: "static/images/uploads"
public_folder: /static
# publish_mode: editorial_workflow
